### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by selfagency** [okcomrade/okcomrade#1]
is this project dead in the water or has there been action behind the scenes that just hasn't been pushed to the repo

**Comment by deathblankets** [comment]
Also wondering :)

**Comment by selfagency** [comment]
I'll take three months silence as "dead."

**Comment by SystemDisc** [comment]
@selfagency The project is not dead. I'm just waiting for enough interest for development to feel worth it to me.

**Comment by selfagency** [comment]
@SystemDisc what kind of help are you looking for? i do node.js and frontend dev.
